version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mongo:
    image: mongo:6.0
    container_name: devcontainer-mongo
    environment:
      MONGO_INITDB_DATABASE: VehicleRentalDb
    # ports:
    #   - 27017:27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 